on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: 'Remove jq'
        run: |
          sudo apt-get purge --auto-remove jq
 
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
        with:
          version: 1.7
          force: true

      - name: 'Check jq'
        # language=sh
        run: |
          which jq
          jq --version
