name: Remove Examples in Official WNM Schema

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get full schema
        run: |
          curl -O https://schemas.wmo.int/wnm/1.0.0/schemas/wis2-notification-message-bundled.json
          
      - name: Delete offending keys in schema file
        run: |
          jq 'del(.properties.links.items.allOf[0].allOf[0].properties.[].example)' wis2-notification-message-bundled.json > wis2-notification-messge.json
          
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update changed files
