# This is a basic workflow to help you get started with Actions

name: UpdateSchema

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get schemas bundle
        id: get_bundle
        run: |
          curl -s https://schemas.wmo.int/wth/a/bundle/wis2-topic-hierarchy-a.zip

