name: Publish WIS2 Notification Messages

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Install mqttx
        run: |
          curl -LO https://www.emqx.com/zh/downloads/MQTTX/1.9.0/mqttx-cli-linux-x64
          sudo install ./mqttx-cli-linux-x64 /usr/local/bin/mqttx

      - name: Send message
        env:
          MQTT_BROKER_HOST: ${{ secrets.MQTT_BROKER_HOST}}
          MQTT_USERNAME: ${{ secrets.MQTT_USERNAME}}
          MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD}}
          
        run: |
          mqttx pub -h $MQTT_BROKER_HOST -p 8883 -l mqtts --insecure -u $MQTT_USERNAME -P $MQTT_PASSWORD -t origin/a/wis2/test -m "from github" 
          
