name: Publish WIS2 Notification Messages

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: mosquitto mosquitto-clients
          version: 1.0
        
      - name: Send message
        env:
          MQTT_BROKER_HOST: ${{ secrets.MQTT_BROKER_HOST}}
          MQTT_USERNAME: ${{ secrets.MQTT_USERNAME}}
          MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD}}
          
        run: |
          mosquitto_pub -h $MQTT_BROKER_HOST -p 8883 --insecure -u $MQTT_USERNAME -P $MQTT_PASSWORD -t origin/a/wis2/test -m "from github" 
          
